// LOGIN 
export const POST_LOGIN_DATA_SAGA = "POST_LOGIN_DATA_SAGA";
export const POST_LOGIN_DATA_SAGA_ERROR = "POST_LOGIN_DATA_SAGA_ERROR"
export const SET_LOGIN_USER_ACTIVE = "SET_LOGIN_USER_ACTIVE"
export const SET_LOGIN_FORM_VISIBLE = "SET_LOGIN_FORM_VISIBLE"
export const SET_LOGIN_USER_LOGOUT = "SET_LOGIN_USER_LOGOUT"

// Register 
export const POST_REGISTER_DATA_SAGA = "POST_REGISTER_DATA_SAGA";
export const POST_REGISTER_DATA_SAGA_ERROR = "POST_REGISTER_DATA_SAGA_ERROR"
export const SET_REGISTER_USER_SUCCESS = "SET_REGISTER_USER_SUCCESS"
export const SET_REGISTER_FORM_VISIBLE = "SET_REGISTER_FORM_VISIBLE"

// Marks
export const GET_DATA_MARKS_SAGA = "GET_DATA_MARKS_SAGA"
export const GET_DATA_MARKS_SUCCESS = "GET_DATA_MARKS_SUCCESS"
export const GET_DATA_MARKS_ERROR = "GET_DATA_MARKS_ERROR"