// Loading Register/Login form.
export const SWITCH_LOGIN_REGISTER_FORM = "SWITCH_LOGIN_REGISTER_FORM";

// LOGIN 
export const POST_LOGIN_DATA_SAGA = "POST_LOGIN_DATA_SAGA";
export const POST_LOGIN_DATA_SAGA_ERROR = "POST_LOGIN_DATA_SAGA_ERROR"
export const SET_LOGIN_USER_ACTIVE = "SET_LOGIN_USER_ACTIVE"